
# This workflow will inspect a pull request to ensure there is a linked issue or a
# valid issue is mentioned in the body. If neither is present it fails the check and adds
# a comment alerting users of this missing requirement.
name: VerifyIssue

on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  pull_request:
    types: [ labeled, synchronize, reopened, edited ]
    branches: main


jobs: 
  labeled_firstgoodissue:
    if: ${{ github.event.label.name == 'firstgoodissue' }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Output linked Issue list
        run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.html_url }}"
          echo "labels: ${{ github.event.pull_request.labels.*.name }}"
          
          
  no_labeled_firstgoodissue:
    if: ${{ github.event.label.name == 'firstgoodissue' }}
    runs-on: ubuntu-latest
    name: A job to say hello1
    steps:
      - name: Output linked Issue list
        run: |
          echo "${{ github.event.pull_request.title }}"
